- route:
    from:
      uri: timer
      parameters:
        timerName: start
      steps:
        - setBody:
            expression:
              simple:
                expression: '{"orderId": ${random(1000)}, "item": "widget", "quantity":
                  ${random(10)}}'
        - to:
            uri: jms
            parameters:
              destinationName: numbers

